// Package sshkey generates ed25519 SSH keypairs for runner-managed VMs.
//
// Each VM gets its own SSH key (registered with Hetzner for cloud-init
// injection + used by the runner to SSH in for health checks and deploys).
//
// We generate the key locally so the private key never leaves the runner
// process — only the public key is uploaded to Hetzner.
package sshkey

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"errors"
	"fmt"
	"strings"
	"time"

	"golang.org/x/crypto/ssh"
)

// Authority is the value used in the authorized_keys comment for keys
// generated by the runner. Helps admins identify runner-managed keys when
// auditing ~/.ssh/authorized_keys or Hetzner console.
const Authority = "runner-generated"

// SSHKeyPair is the result of Generate. The PrivateKeyPEM is what the runner
// stores in its secrets store; the AuthorizedKey is what gets shipped to
// Hetzner + written to the VM's authorized_keys.
type SSHKeyPair struct {
	// PrivateKey is the raw ed25519 private key (64 bytes: seed || public).
	// Kept in memory only; never written to disk by this package.
	PrivateKey ed25519.PrivateKey
	// PublicKey is the raw ed25519 public key (32 bytes).
	PublicKey ed25519.PublicKey

	// PrivateKeyOpenSSH is the OpenSSH PEM encoding of the private key
	// (matches `ssh-keygen -o -a 100`). Suitable for storing in the runner's
	// secrets store (Phase 1B) and for use with the SSH client.
	PrivateKeyOpenSSH string

	// AuthorizedKey is the authorized_keys line:
	//   ssh-ed25519 <base64> runner-generated@<unix-timestamp>
	AuthorizedKey string

	// Fingerprint is the OpenSSH-style fingerprint:
	//   SHA256:<base64>
	Fingerprint string

	// GeneratedAt is the unix timestamp the key was generated.
	GeneratedAt time.Time
}

// Generate creates a new ed25519 keypair.
//
// The returned SSHKeyPair is suitable for:
//   - Uploading PublicKey + AuthorizedKey to Hetzner (CreateSSHKey)
//   - Using PrivateKeyOpenSSH with the SSH client in Phase 1B
//   - Storing in the runner's secrets store for later re-use
//
// Errors are returned only for entropy source failure (extremely rare on
// Linux, which uses getrandom(2)).
func Generate() (*SSHKeyPair, error) {
	return GenerateAt(time.Now())
}

// GenerateAt is like Generate but with an explicit timestamp. Useful for
// deterministic tests.
func GenerateAt(now time.Time) (*SSHKeyPair, error) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("sshkey: ed25519.GenerateKey: %w", err)
	}

	authorizedKey, err := marshalAuthorizedKey(pub, now)
	if err != nil {
		return nil, fmt.Errorf("sshkey: marshalAuthorizedKey: %w", err)
	}

	openSSHPEM, err := marshalOpenSSHPrivateKey(priv, comment)
	if err != nil {
		return nil, fmt.Errorf("sshkey: marshalOpenSSHPrivateKey: %w", err)
	}

	return &SSHKeyPair{
		PrivateKey:         priv,
		PublicKey:          pub,
		PrivateKeyOpenSSH:  openSSHPEM,
		AuthorizedKey:      authorizedKey,
		Fingerprint:        Fingerprint(pub),
		GeneratedAt:        now,
	}, nil
}

// comment is the embedded comment inside the OpenSSH PEM. Matches what
// `ssh-keygen -C` produces.
var comment = Authority

// Fingerprint returns the OpenSSH SHA256 fingerprint of a public key.
//
// Format: `SHA256:<base64>` (no colons, no spaces) — matches what
// `ssh-keygen -lf <pub>` prints and what Hetzner shows in the console.
//
// The fingerprint is computed over the SSH wire-format encoding of the
// public key (RFC 4253 §6.6), NOT the raw key bytes. This matches OpenSSH's
// behavior and makes our fingerprints round-trip through `ssh.ParseAuthorizedKey`.
func Fingerprint(pub ed25519.PublicKey) string {
	sshPub, err := ssh.NewPublicKey(pub)
	if err != nil {
		// Should be impossible for a well-formed ed25519.PublicKey, but fall
		// back to the raw-bytes hash so callers still get a stable string.
		sum := sha256.Sum256(pub)
		return "SHA256:" + base64.StdEncoding.EncodeToString(sum[:])
	}
	return ssh.FingerprintSHA256(sshPub)
}

// marshalAuthorizedKey serializes a public key to the authorized_keys line:
//
//	ssh-ed25519 <base64> <comment>
//
// where <comment> is "<authority>@<unix-timestamp>".
func marshalAuthorizedKey(pub ed25519.PublicKey, now time.Time) (string, error) {
	sshPub, err := ssh.NewPublicKey(pub)
	if err != nil {
		return "", fmt.Errorf("ssh.NewPublicKey: %w", err)
	}
	authKey := strings.TrimRight(string(ssh.MarshalAuthorizedKey(sshPub)), "\n")
	return fmt.Sprintf("%s %s@%d", authKey, Authority, now.Unix()), nil
}

// marshalOpenSSHPrivateKey serializes an ed25519 private key in OpenSSH PEM
// format (compatible with `ssh-keygen -o -a 100`).
//
// Phase 1B will use the resulting PEM with the runner's SSH client. We do
// NOT encrypt the PEM with a passphrase here — that decision is deferred to
// Phase 1B once we know how the runner will store secrets.
func marshalOpenSSHPrivateKey(priv ed25519.PrivateKey, comment string) (string, error) {
	pemBytes, err := ssh.MarshalPrivateKey(priv, comment)
	if err != nil {
		return "", fmt.Errorf("ssh.MarshalPrivateKey: %w", err)
	}
	return string(pem.EncodeToMemory(pemBytes)), nil
}

// PublicKeyFromAuthorizedKey parses an authorized_keys line back into a
// usable ssh.PublicKey. Used by the runner to verify a key uploaded to
// Hetzner matches the locally-generated one.
//
// Returns ErrInvalidAuthorizedKey for any parse failure.
var ErrInvalidAuthorizedKey = errors.New("sshkey: invalid authorized_keys line")

func PublicKeyFromAuthorizedKey(line string) (ssh.PublicKey, error) {
	pub, _, _, _, err := ssh.ParseAuthorizedKey([]byte(line))
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrInvalidAuthorizedKey, err)
	}
	return pub, nil
}

// FingerprintFromAuthorizedKey is a convenience that parses the line and
// returns its SHA256 fingerprint.
func FingerprintFromAuthorizedKey(line string) (string, error) {
	pub, err := PublicKeyFromAuthorizedKey(line)
	if err != nil {
		return "", err
	}
	// ssh.PublicKey has a fingerprint helper that matches ssh-keygen output.
	return ssh.FingerprintSHA256(pub), nil
}

// MustGenerate is a test helper that panics on error. DO NOT use in library code.
func MustGenerate() *SSHKeyPair {
	k, err := Generate()
	if err != nil {
		panic(err)
	}
	return k
}

// AsEd25519PublicKey extracts the ed25519.PublicKey from an ssh.PublicKey.
// Returns an error if the underlying key is not ed25519.
func AsEd25519PublicKey(pub ssh.PublicKey) (ed25519.PublicKey, error) {
	cryptoPub, ok := pub.(ssh.CryptoPublicKey)
	if !ok {
		return nil, errors.New("sshkey: ssh.PublicKey does not implement ssh.CryptoPublicKey")
	}
	raw, ok := cryptoPub.CryptoPublicKey().(ed25519.PublicKey)
	if !ok {
		return nil, errors.New("sshkey: underlying key is not ed25519")
	}
	return raw, nil
}

// AsEd25519PrivateKey extracts the ed25519.PrivateKey from a parsed
// ssh.PemDecryptFunc-decoded key. Reserved for Phase 1B.
func AsEd25519PrivateKey(priv any) (ed25519.PrivateKey, error) {
	switch k := priv.(type) {
	case ed25519.PrivateKey:
		return k, nil
	case *ed25519.PrivateKey:
		if k == nil {
			return nil, errors.New("sshkey: nil ed25519 private key")
		}
		return *k, nil
	default:
		return nil, fmt.Errorf("sshkey: not an ed25519 private key, got %T", priv)
	}
}

// MarshalPKCS8 marshals an ed25519 private key to PKCS#8 DER. Reserved for
// Phase 1B if the runner needs to embed the key in a non-OpenSSH secret store.
func MarshalPKCS8(priv ed25519.PrivateKey) ([]byte, error) {
	der, err := x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		return nil, fmt.Errorf("sshkey: MarshalPKCS8PrivateKey: %w", err)
	}
	return der, nil
}