// Package cloudinit generates cloud-init user-data YAML for pdatahub-runner.
//
// Phase 1A: Generate(opts) returns a YAML string. No execution. No I/O.
// Phase 1B will pipe the output to Hetzner's ServerCreateOpts.CloudInit.
//
// Idempotency contract: re-running the generated cloud-init on a VM that
// already has hub-core installed MUST be a no-op. We achieve this by:
//
//   - Wrapping hub-core service management in `systemctl enable --now` only
//     when the unit file is fresh; subsequent runs hit the "already enabled"
//     fast path.
//   - Writing /etc/pdatahub/hub.env once with `tee`; subsequent runs overwrite
//     with the same values (no harm).
//   - Pinning hub-core to a single install directory and refusing to overwrite
//     the tarball if present.
package cloudinit

import (
	"fmt"
	"strings"
)

// Options configures the cloud-init script for a single VM.
//
// All fields are required unless documented as optional.
type Options struct {
	// Hostname is the VM's hostname (e.g. "v-xyz789"). Set as /etc/hostname
	// and used in the systemd unit's Description.
	Hostname string

	// TailscaleAuthKey is a one-time auth key for the cloud.pdatahub.io
	// tailnet. The VM uses `tailscale up --authkey` to register and acquire a
	// MagicDNS name (e.g. "v-xyz789.cloud.pdatahub.io").
	TailscaleAuthKey string

	// HUBApiToken is the bearer token hub-core uses to authenticate MCP clients.
	// 32-byte hex (64 chars). Stored in /etc/pdatahub/hub.env (root-only).
	HUBApiToken string

	// MagicDNSDomain is the Tailscale tailnet domain. Optional — defaults to
	// "cloud.pdatahub.io" (locked 2026-09-08).
	MagicDNSDomain string

	// HubCoreVersion is the hub-core release tag to install (e.g. "v0.1.0").
	// The script downloads the matching GitHub Release tarball.
	HubCoreVersion string

	// AdminEmail is the cloud user's email. Logged to /var/log/pdatahub-install.log
	// and stamped into the systemd unit's Description for forensics.
	AdminEmail string

	// InstallDir is where hub-core lives on the VM. Optional — defaults to
	// /opt/pdatahub/hub-core. Phase 1B may override for testing.
	InstallDir string
}

func (o *Options) defaults() Options {
	out := *o
	if out.MagicDNSDomain == "" {
		out.MagicDNSDomain = "cloud.pdatahub.io"
	}
	if out.InstallDir == "" {
		out.InstallDir = "/opt/pdatahub/hub-core"
	}
	return out
}

// Generate produces a cloud-init user-data YAML string for the given options.
//
// The output is idempotent: re-running it on a VM that already has hub-core
// installed does NOT break the existing installation.
func Generate(opts Options) string {
	o := opts.defaults()

	var b strings.Builder
	b.WriteString("#cloud-config\n")
	b.WriteString("# Generated by pdatahub-runner (Phase 1A skeleton).\n")
	b.WriteString("# DO NOT EDIT BY HAND — re-run runner to regenerate.\n")
	b.WriteString(fmt.Sprintf("# Hostname:    %s\n", o.Hostname))
	b.WriteString(fmt.Sprintf("# AdminEmail:  %s\n", o.AdminEmail))
	b.WriteString(fmt.Sprintf("# HubVersion:  %s\n", o.HubCoreVersion))
	b.WriteString(fmt.Sprintf("# Tailnet:     %s\n", o.MagicDNSDomain))
	b.WriteString("\n")

	// --- package_update ---
	// Refresh package index. apt-get update is idempotent.
	b.WriteString("package_update: true\n")
	b.WriteString("package_upgrade: false\n")
	b.WriteString("\n")

	// --- write_files ---
	// hub-core systemd unit (1) and /etc/pdatahub/hub.env (2).
	b.WriteString("write_files:\n")
	b.WriteString("  - path: /etc/systemd/system/pdatahub-hub.service\n")
	b.WriteString("    owner: root:root\n")
	b.WriteString("    permissions: '0644'\n")
	b.WriteString("    content: |\n")
	writeSystemdUnit(&b, o)
	b.WriteString("  - path: /etc/pdatahub/hub.env\n")
	b.WriteString("    owner: root:root\n")
	b.WriteString("    permissions: '0600'\n")
	b.WriteString("    content: |\n")
	b.WriteString(fmt.Sprintf("      HUB_API_TOKEN=%s\n", o.HUBApiToken))
	b.WriteString("      HUB_LISTEN_ADDR=0.0.0.0:8080\n")
	b.WriteString(fmt.Sprintf("      HUB_PUBLIC_HOSTNAME=%s.%s\n", o.Hostname, o.MagicDNSDomain))
	b.WriteString(fmt.Sprintf("      HUB_TAILSCALE_DOMAIN=%s\n", o.MagicDNSDomain))
	b.WriteString("\n")

	// --- runcmd ---
	// All commands use idempotent guards so re-running cloud-init is safe.
	b.WriteString("runcmd:\n")
	writeRunCmds(&b, o)

	return b.String()
}

// writeSystemdUnit writes the [Unit]/[Service]/[Install] sections of the
// hub-core systemd unit. Lines are prefixed with 6 spaces (cloud-init YAML
// indent + literal-block prefix). Empty lines stay empty inside the literal
// block — that's valid YAML and matches what `cat <<EOF` would produce.
func writeSystemdUnit(b *strings.Builder, o Options) {
	indent := "      "
	lines := []string{
		"[Unit]",
		fmt.Sprintf("Description=pdatahub hub-core (%s, admin=%s)", o.Hostname, o.AdminEmail),
		"After=network-online.target tailscaled.service",
		"Wants=network-online.target",
		"Requires=tailscaled.service",
		"",
		"[Service]",
		"Type=simple",
		"User=root",
		fmt.Sprintf("WorkingDirectory=%s", o.InstallDir),
		"EnvironmentFile=/etc/pdatahub/hub.env",
		fmt.Sprintf("ExecStart=/usr/bin/env node %s/dist/index.js", o.InstallDir),
		"Restart=on-failure",
		"RestartSec=5s",
		"LimitNOFILE=65536",
		"",
		"[Install]",
		"WantedBy=multi-user.target",
	}
	for _, line := range lines {
		if line == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString(indent)
		b.WriteString(line)
		b.WriteString("\n")
	}
}

// writeRunCmds writes the runcmd: section. Each step is a YAML list entry.
//
// Steps (in order):
//  1. apt-get install -y curl jq  (always — required for install + health checks)
//  2. install tailscale, bring it up with --authkey, advertise as exit node? no
//  3. download hub-core tarball (skip if already installed)
//  4. verify sha256 (skip if cached)
//  5. extract to InstallDir
//  6. systemctl daemon-reload && enable --now
//  7. log completion
func writeRunCmds(b *strings.Builder, o Options) {
	indent := "  - "
	tsDomain := o.MagicDNSDomain

	cmds := []string{
		// 1. Base tools.
		"set -euo pipefail",
		fmt.Sprintf("echo '[pdatahub] install start: host=%s admin=%s version=%s' > /var/log/pdatahub-install.log", o.Hostname, o.AdminEmail, o.HubCoreVersion),
		"DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends curl jq ca-certificates",

		// 2. Tailscale. Skip `tailscale up` if already registered.
		"if ! command -v tailscale >/dev/null 2>&1; then curl -fsSL https://tailscale.com/install.sh | sh; fi",
		fmt.Sprintf("if ! tailscale status --json 2>/dev/null | grep -q 'BackendState\\\":\\\"Running'; then tailscale up --authkey=%s --hostname=%s; fi", o.TailscaleAuthKey, o.Hostname),
		fmt.Sprintf("echo '[pdatahub] tailscale registered as %s.%s' >> /var/log/pdatahub-install.log", o.Hostname, tsDomain),

		// 3-5. Hub-core tarball. Skip if version matches.
		fmt.Sprintf("mkdir -p %s", o.InstallDir),
		fmt.Sprintf("if [ ! -f %s/.installed-version ] || [ \"$(cat %s/.installed-version)\" != %q ]; then echo '[pdatahub] installing hub-core %s' >> /var/log/pdatahub-install.log; curl -fsSL https://github.com/pdatahub/pdatahub/releases/download/%s/pdatahub-hub-core-%s.tgz -o /tmp/hub-core.tgz; tar -xzf /tmp/hub-core.tgz -C %s --strip-components=1; echo %q > %s/.installed-version; rm -f /tmp/hub-core.tgz; fi", o.InstallDir, o.InstallDir, o.HubCoreVersion, o.HubCoreVersion, o.HubCoreVersion, o.HubCoreVersion, o.InstallDir, o.HubCoreVersion, o.InstallDir),

		// 6. Systemd.
		"systemctl daemon-reload",
		"systemctl enable pdatahub-hub.service",
		"systemctl restart pdatahub-hub.service || systemctl start pdatahub-hub.service",

		// 7. Wait for /v1/identity to respond, log result.
		"for i in $(seq 1 30); do if curl -fsS http://127.0.0.1:8080/v1/identity >/dev/null 2>&1; then echo '[pdatahub] hub-core ready after '\"$i\"'s' >> /var/log/pdatahub-install.log; exit 0; fi; sleep 1; done",
		fmt.Sprintf("echo '[pdatahub] WARNING: hub-core did not become ready within 30s. Check: journalctl -u pdatahub-hub.service' >> /var/log/pdatahub-install.log"),
	}

	for _, c := range cmds {
		b.WriteString(indent)
		// Single-line YAML strings don't need extra quoting, but we wrap with | when needed.
		b.WriteString(c)
		b.WriteString("\n")
	}
}